/**
 * Mock data for Points & Offers feature
 * Designed to cleanly mirror future backend API contracts
 */

export const INITIAL_USER_POINTS = {
  availablePoints: 350,
  expiringPoints: 50,
  expiryDate: "31/12/2024",
  totalAccumulated: 400,
  totalRedeemed: 50,
  expiringBefore: "20/09/2026",
}

export const EARNING_METHODS = [
  {
    id: "earn-review",
    title: "Đánh giá khóa học",
    subtitle: "Sau mỗi lớp học kết thúc",
    points: 50,
    icon: "star",
    badgeColor: "rose",
  },
  {
    id: "earn-referral",
    title: "Giới thiệu bạn bè",
    subtitle: "Bạn bè đăng ký thành công",
    points: 100,
    icon: "user-plus",
    badgeColor: "rose",
  },
  {
    id: "earn-milestone",
    title: "Hoàn thành lộ trình",
    subtitle: "Hoàn thành toàn bộ khóa học",
    points: 200,
    icon: "trophy",
    badgeColor: "rose",
  },
]

export const AVAILABLE_VOUCHERS = [
  {
    id: "v-1",
    title: "Voucher Giảm 20% Học Phí Khóa Giao Tiếp",
    badge: "Giảm 20%",
    category: "course",
    description: "Áp dụng cho học viên đăng ký mới khóa Giao tiếp Tiếng Anh Cơ Bản",
    expiryDate: "31/12/2024",
    pointsRequired: 150,
    percentRedeemed: 45,
    status: "available",
    iconType: "coffee",
  },
  {
    id: "v-2",
    title: "Voucher Giảm 500k Khóa Luyện Thi IELTS",
    badge: "Giảm 500k",
    category: "ielts",
    description: "Áp dụng cho mọi học viên đăng ký lộ trình IELTS 6.5+",
    expiryDate: "15/11/2024",
    pointsRequired: 250,
    percentRedeemed: 80,
    status: "available",
    iconType: "book",
  },
  {
    id: "v-3",
    title: "Voucher Miễn Phí Test Trình Độ",
    badge: "Miễn phí",
    category: "test",
    description: "Nhận 1 buổi test trình độ 1-1 với giáo viên bản ngữ",
    expiryDate: "30/10/2024",
    pointsRequired: 50,
    percentRedeemed: 100,
    status: "out_of_stock",
    iconType: "headphones",
  },
  {
    id: "v-4",
    title: "Tặng 1 buổi học thử 1-on-1",
    badge: "HOT",
    category: "trial",
    description: "Áp dụng cho mọi khóa học giao tiếp và phát âm phản xạ",
    expiryDate: "15/11/2024",
    pointsRequired: 1000,
    percentRedeemed: 12,
    status: "available",
    iconType: "book",
  },
  {
    id: "v-5",
    title: "Voucher Giảm 15% Khóa Luyện Phát Âm Mỹ",
    badge: "Giảm 15%",
    category: "course",
    description: "Khóa học độc quyền sửa lỗi ngữ điệu và phát âm chuẩn IPA",
    expiryDate: "28/12/2024",
    pointsRequired: 200,
    percentRedeemed: 60,
    status: "available",
    iconType: "sparkles",
  },
  {
    id: "v-6",
    title: "Voucher Giảm 300k Đăng Ký Gói VIP 6 Tháng",
    badge: "Giảm 300k",
    category: "package",
    description: "Áp dụng khi nâng cấp gói thành viên Pro hoặc VIP",
    expiryDate: "10/01/2025",
    pointsRequired: 300,
    percentRedeemed: 25,
    status: "available",
    iconType: "gift",
  },
]

export const INITIAL_VAULT_VOUCHERS = [
  {
    id: "vault-1",
    code: "CAT-1XY20",
    title: "Giảm giá học phí IELTS",
    discountTag: "20%",
    status: "unused",
    expiryDate: "31/12/2024",
    badge: "Chưa dùng",
    description: "Áp dụng giảm 20% học phí khi thanh toán khóa học IELTS bất kỳ",
    createdAt: "15/08/2024",
  },
  {
    id: "vault-2",
    code: "CS-GT100K",
    title: "Voucher Khóa Giao tiếp cơ bản",
    discountTag: "100k",
    status: "unused",
    expiryDate: "20/12/2024",
    badge: "Hot deal",
    description: "Trừ trực tiếp 100.000 VNĐ vào hóa đơn khóa học Giao tiếp",
    createdAt: "18/08/2024",
  },
  {
    id: "vault-3",
    code: "CS-NP10P",
    title: "Ưu đãi khóa ngữ pháp",
    discountTag: "10%",
    status: "used",
    usedDate: "15/10/2024",
    expiryDate: "30/11/2024",
    badge: "Đã dùng",
    description: "Đã áp dụng thành công cho đơn hàng #ORD-88231",
    createdAt: "01/08/2024",
  },
  {
    id: "vault-4",
    code: "CS-SUMMER",
    title: "Khuyến mãi mùa hè",
    discountTag: "5%",
    status: "expired",
    expiryDate: "10/08/2024",
    badge: "Hết hạn",
    description: "Hết hạn sử dụng vào ngày 10/08/2024",
    createdAt: "01/06/2024",
  },
]

export const INITIAL_POINT_HISTORY = [
  {
    id: "tx-1",
    title: "Hoàn thành khóa học A",
    subtitle: "Tích lũy hoàn tất",
    date: "20/08/2024 14:30",
    points: 50,
    type: "earn",
    icon: "check",
  },
  {
    id: "tx-2",
    title: "Đổi Voucher Giảm 15k",
    subtitle: "Sử dụng điểm",
    date: "18/08/2024 10:15",
    points: -200,
    type: "spend",
    icon: "exchange",
  },
  {
    id: "tx-3",
    title: "Tham gia challenge",
    subtitle: "Thưởng thành tích",
    date: "05/08/2024 17:00",
    points: 20,
    type: "earn",
    icon: "trophy",
  },
  {
    id: "tx-4",
    title: "Đổi Voucher Giảm 20%",
    subtitle: "Sử dụng điểm",
    date: "15/08/2024 14:30",
    points: -150,
    type: "spend",
    icon: "exchange",
  },
  {
    id: "tx-5",
    title: "Hoàn thành khóa Giao tiếp",
    subtitle: "Tích lũy hoàn tất",
    date: "10/08/2024 09:15",
    points: 200,
    type: "earn",
    icon: "cap",
  },
  {
    id: "tx-6",
    title: "Đánh giá khóa học",
    subtitle: "Đánh giá giáo viên và bài giảng",
    date: "05/08/2024 16:45",
    points: 50,
    type: "earn",
    icon: "star",
  },
]
