export const PLAN_FEATURES = {
  ALLOW_PRIVATE_ROOMS: "ALLOW_PRIVATE_ROOMS",
  BEAUTY_FILTER: "BEAUTY_FILTER",
  MAX_ACTIVE_ROOMS: "MAX_ACTIVE_ROOMS",
  MAX_AI_MESSAGES: "MAX_AI_MESSAGES",
  MAX_PARTICIPANTS: "MAX_PARTICIPANTS",
  MAX_REELS_UPLOAD: "MAX_REELS_UPLOAD",
  MAX_STORAGE_MB: "MAX_STORAGE_MB",
  SUPPORT_PRIORITY: "SUPPORT_PRIORITY"
}
