export const PLAN_FEATURES = {
  ALLOW_RECORDING: "ALLOW_RECORDING",
  BEAUTY_FILTER: "BEAUTY_FILTER",
  MAX_ACTIVE_ROOMS: "MAX_ACTIVE_ROOMS",
  MAX_ACTIVE_STORIES: "MAX_ACTIVE_STORIES",
  MAX_AI_MESSAGES: "MAX_AI_MESSAGES",
  MAX_AI_DAILY_TOKENS: "MAX_AI_DAILY_TOKENS",
  MAX_PARTICIPANTS_IN_CUSTOM_ROOMS: "MAX_PARTICIPANTS_IN_CUSTOM_ROOMS",
  MAX_REELS_UPLOAD: "MAX_REELS_UPLOAD",
  MAX_RECORDING_STORAGE_MB: "MAX_RECORDING_STORAGE_MB",
  SUPPORT_PRIORITY: "SUPPORT_PRIORITY",
  ALLOW_PLACEMENT_TEST: "ALLOW_PLACEMENT_TEST",
}
