export { default as LandingPageLogo } from "./logo/landing-page-logo.svg";
export { default as LandingPageIcon } from "./logo/landing-page-icon.svg";
export { default as Element1 } from "./background/element-1.png";
export { default as Element2 } from "./background/element-2.png";
export { default as Element3 } from "./background/element-3.png";
export { default as Element4 } from "./background/element-4.png";
export { default as Element5 } from "./background/element-5.png";
export { default as Element6 } from "./background/element-6.png";
export { default as Screen } from "./screen.png";
export { default as Map } from "./map.png";
// export { default as Partner1 } from "./partners/partner-1.png";
// export { default as Partner2 } from "./partners/partner-2.png";
// export { default as Partner3 } from "./partners/partner-3.png";
// export { default as Partner4 } from "./partners/partner-4.png";
// export { default as Partner5 } from "./partners/partner-5.png";
export { default as CulturalRoots } from "./partners/Cultural_Roots.png";
export { default as FPTU } from "./partners/FPTU.png";
export { default as Go4AI } from "./partners/Go4AI.png";
export { default as ITesol } from "./partners/I_Tesol.png";
export { default as IntracomU } from "./partners/IntracomU.png";
export { default as JCITrevi } from "./partners/JCI_Trevi.png";
export { default as LightLearning } from "./partners/Light_Learning.png";
export { default as MeduEnglish } from "./partners/Medu_English.png";
export { default as SpeakUpGlobal } from "./partners/Speak_Up_Global.png";
export { default as HubNetwork } from "./partners/Hub_Network.png";
export { default as QTEDU } from "./partners/QTEDU.png";
export { default as EZTalking } from "./partners/EZTalking.png";
