export const HSK_LEVELS = [1, 2, 3, 4, 5, 6]

export const HSK_BANK = {
  1: {
    questions: [
      {
        id: "q1-name",
        level: 1,
        hanzi: "你好，你叫什么名字？",
        pinyin: "Nǐ hǎo, nǐ jiào shénme míngzi?",
        vi: "Xin chào, bạn tên là gì?",
      },
      {
        id: "q1-country",
        level: 1,
        hanzi: "你是哪国人？",
        pinyin: "Nǐ shì nǎ guó rén?",
        vi: "Bạn là người nước nào?",
      },
      {
        id: "q1-family",
        level: 1,
        hanzi: "你家有几口人？",
        pinyin: "Nǐ jiā yǒu jǐ kǒu rén?",
        vi: "Gia đình bạn có mấy người?",
      },
    ],
    vocabulary: [
      { word: "我", pinyin: "wǒ", vi: "tôi", level: 1, difficulty: 1 },
      { word: "你", pinyin: "nǐ", vi: "bạn", level: 1, difficulty: 1 },
      { word: "他", pinyin: "tā", vi: "anh ấy", level: 1, difficulty: 1 },
      { word: "是", pinyin: "shì", vi: "là", level: 1, difficulty: 1 },
      { word: "有", pinyin: "yǒu", vi: "có", level: 1, difficulty: 1 },
      { word: "不", pinyin: "bù", vi: "không", level: 1, difficulty: 1 },
      { word: "很", pinyin: "hěn", vi: "rất", level: 1, difficulty: 1 },
      { word: "学生", pinyin: "xuéshēng", vi: "học sinh", level: 1, difficulty: 1.2 },
      { word: "老师", pinyin: "lǎoshī", vi: "giáo viên", level: 1, difficulty: 1.2 },
      { word: "朋友", pinyin: "péngyou", vi: "bạn bè", level: 1, difficulty: 1.2 },
      { word: "家", pinyin: "jiā", vi: "nhà", level: 1, difficulty: 1.1 },
      { word: "中国", pinyin: "Zhōngguó", vi: "Trung Quốc", level: 1, difficulty: 1.3 },
      { word: "喜欢", pinyin: "xǐhuan", vi: "thích", level: 1, difficulty: 1.3 },
      { word: "名字", pinyin: "míngzi", vi: "tên", level: 1, difficulty: 1.2 },
      { word: "今天", pinyin: "jīntiān", vi: "hôm nay", level: 1, difficulty: 1.2 },
      { word: "天气", pinyin: "tiānqì", vi: "thời tiết", level: 1, difficulty: 1.4 },
      { word: "吃", pinyin: "chī", vi: "ăn", level: 1, difficulty: 1.1 },
      { word: "去", pinyin: "qù", vi: "đi", level: 1, difficulty: 1.1 },
      { word: "说", pinyin: "shuō", vi: "nói", level: 1, difficulty: 1.1 },
      { word: "谢谢", pinyin: "xièxie", vi: "cảm ơn", level: 1, difficulty: 1.2 },
    ],
    grammar: [
      { id: "g1-shi", level: 1, label: "是字句", pattern: /是/ },
      { id: "g1-you", level: 1, label: "有字句", pattern: /有/ },
      { id: "g1-hen", level: 1, label: "很 + 形容词", pattern: /很/ },
      { id: "g1-ma", level: 1, label: "吗问句", pattern: /吗/ },
      { id: "g1-bu", level: 1, label: "不否定", pattern: /不/ },
    ],
    fallbackAnswers: [
      { hanzi: "我叫小明，我是学生。", pinyin: "Wǒ jiào Xiǎomíng, wǒ shì xuéshēng.", vi: "Tôi tên Tiểu Minh, tôi là học sinh." },
      { hanzi: "我是中国人，我很喜欢这里。", pinyin: "Wǒ shì Zhōngguó rén, wǒ hěn xǐhuan zhèlǐ.", vi: "Tôi là người Trung Quốc, tôi rất thích nơi này." },
    ],
  },
  2: {
    questions: [
      {
        id: "q2-weather",
        level: 2,
        hanzi: "今天天气怎么样？",
        pinyin: "Jīntiān tiānqì zěnmeyàng?",
        vi: "Hôm nay thời tiết thế nào?",
      },
      {
        id: "q2-hobby",
        level: 2,
        hanzi: "你平时喜欢做什么？",
        pinyin: "Nǐ píngshí xǐhuan zuò shénme?",
        vi: "Bình thường bạn thích làm gì?",
      },
      {
        id: "q2-yesterday",
        level: 2,
        hanzi: "你昨天去哪儿了？",
        pinyin: "Nǐ zuótiān qù nǎr le?",
        vi: "Hôm qua bạn đã đi đâu?",
      },
    ],
    vocabulary: [
      { word: "因为", pinyin: "yīnwèi", vi: "bởi vì", level: 2, difficulty: 1.3 },
      { word: "所以", pinyin: "suǒyǐ", vi: "cho nên", level: 2, difficulty: 1.3 },
      { word: "已经", pinyin: "yǐjīng", vi: "đã", level: 2, difficulty: 1.6 },
      { word: "正在", pinyin: "zhèngzài", vi: "đang", level: 2, difficulty: 1.6 },
      { word: "觉得", pinyin: "juéde", vi: "cảm thấy", level: 2, difficulty: 1.5 },
      { word: "时候", pinyin: "shíhou", vi: "lúc", level: 2, difficulty: 1.4 },
      { word: "一起", pinyin: "yìqǐ", vi: "cùng nhau", level: 2, difficulty: 1.3 },
      { word: "周末", pinyin: "zhōumò", vi: "cuối tuần", level: 2, difficulty: 1.4 },
      { word: "时间", pinyin: "shíjiān", vi: "thời gian", level: 2, difficulty: 1.4 },
      { word: "打算", pinyin: "dǎsuàn", vi: "dự định", level: 2, difficulty: 1.7 },
      { word: "旅游", pinyin: "lǚyóu", vi: "du lịch", level: 2, difficulty: 1.5 },
      { word: "运动", pinyin: "yùndòng", vi: "vận động", level: 2, difficulty: 1.5 },
      { word: "可以", pinyin: "kěyǐ", vi: "có thể", level: 2, difficulty: 1.3 },
      { word: "但是", pinyin: "dànshì", vi: "nhưng", level: 2, difficulty: 1.4 },
      { word: "比较", pinyin: "bǐjiào", vi: "tương đối", level: 2, difficulty: 1.6 },
      { word: "昨天", pinyin: "zuótiān", vi: "hôm qua", level: 2, difficulty: 1.3 },
      { word: "身体", pinyin: "shēntǐ", vi: "cơ thể", level: 2, difficulty: 1.6 },
      { word: "健康", pinyin: "jiànkāng", vi: "khỏe mạnh", level: 2, difficulty: 1.7 },
    ],
    grammar: [
      { id: "g2-le", level: 2, label: "了完成态", pattern: /了/ },
      { id: "g2-zhengzai", level: 2, label: "正在进行", pattern: /正在/ },
      { id: "g2-yijing", level: 2, label: "已经", pattern: /已经/ },
      { id: "g2-guo", level: 2, label: "过经历态", pattern: /过/ },
      { id: "g2-yinwei", level: 2, label: "因为…所以…", pattern: /因为.*所以/ },
    ],
    fallbackAnswers: [
      { hanzi: "今天天气很好，我想去公园运动。", pinyin: "Jīntiān tiānqì hěn hǎo, wǒ xiǎng qù gōngyuán yùndòng.", vi: "Hôm nay thời tiết đẹp, tôi muốn ra công viên vận động." },
      { hanzi: "因为周末有时间，所以我和朋友一起去旅游。", pinyin: "Yīnwèi zhōumò yǒu shíjiān, suǒyǐ wǒ hé péngyou yìqǐ qù lǚyóu.", vi: "Vì cuối tuần có thời gian nên tôi cùng bạn đi du lịch." },
    ],
  },
  3: {
    questions: [
      {
        id: "q3-hardest",
        level: 3,
        hanzi: "你觉得学中文最难的地方是什么？",
        pinyin: "Nǐ juéde xué Zhōngwén zuì nán de dìfang shì shénme?",
        vi: "Bạn thấy chỗ khó nhất khi học tiếng Trung là gì?",
      },
      {
        id: "q3-weekend",
        level: 3,
        hanzi: "如果周末有空，你会怎么安排？",
        pinyin: "Rúguǒ zhōumò yǒu kòng, nǐ huì zěnme ānpái?",
        vi: "Nếu cuối tuần rảnh, bạn sẽ sắp xếp thế nào?",
      },
      {
        id: "q3-dish",
        level: 3,
        hanzi: "请介绍一下你最喜欢的一道中国菜。",
        pinyin: "Qǐng jièshào yīxià nǐ zuì xǐhuan de yī dào Zhōngguó cài.",
        vi: "Hãy giới thiệu một món ăn Trung Quốc bạn thích nhất.",
      },
    ],
    vocabulary: [
      { word: "经验", pinyin: "jīngyàn", vi: "kinh nghiệm", level: 3, difficulty: 2 },
      { word: "选择", pinyin: "xuǎnzé", vi: "lựa chọn", level: 3, difficulty: 1.9 },
      { word: "影响", pinyin: "yǐngxiǎng", vi: "ảnh hưởng", level: 3, difficulty: 2.1 },
      { word: "方法", pinyin: "fāngfǎ", vi: "phương pháp", level: 3, difficulty: 1.8 },
      { word: "习惯", pinyin: "xíguàn", vi: "thói quen", level: 3, difficulty: 1.9 },
      { word: "提高", pinyin: "tígāo", vi: "nâng cao", level: 3, difficulty: 1.8 },
      { word: "交流", pinyin: "jiāoliú", vi: "giao lưu", level: 3, difficulty: 2 },
      { word: "文化", pinyin: "wénhuà", vi: "văn hóa", level: 3, difficulty: 1.8 },
      { word: "环境", pinyin: "huánjìng", vi: "môi trường", level: 3, difficulty: 1.9 },
      { word: "努力", pinyin: "nǔlì", vi: "nỗ lực", level: 3, difficulty: 1.6 },
      { word: "安排", pinyin: "ānpái", vi: "sắp xếp", level: 3, difficulty: 1.8 },
      { word: "遇到", pinyin: "yùdào", vi: "gặp phải", level: 3, difficulty: 1.8 },
      { word: "解决", pinyin: "jiějué", vi: "giải quyết", level: 3, difficulty: 1.9 },
      { word: "参加", pinyin: "cānjiā", vi: "tham gia", level: 3, difficulty: 1.8 },
      { word: "认为", pinyin: "rènwéi", vi: "cho rằng", level: 3, difficulty: 1.9 },
      { word: "发展", pinyin: "fāzhǎn", vi: "phát triển", level: 3, difficulty: 1.8 },
    ],
    grammar: [
      { id: "g3-ba", level: 3, label: "把字句", pattern: /把/ },
      { id: "g3-bei", level: 3, label: "被字句", pattern: /被/ },
      { id: "g3-yueyue", level: 3, label: "越…越…", pattern: /越.+越/ },
      { id: "g3-yibian", level: 3, label: "一边…一边…", pattern: /一边.+一边/ },
      { id: "g3-ruguo", level: 3, label: "如果…就…", pattern: /如果.*就/ },
    ],
    fallbackAnswers: [
      { hanzi: "我觉得最难的是发音，因为声调很容易搞错。", pinyin: "Wǒ juéde zuì nán de shì fāyīn, yīnwèi shēngdiào hěn róngyì gǎocuò.", vi: "Tôi thấy khó nhất là phát âm vì thanh điệu rất dễ sai." },
      { hanzi: "如果把时间安排好，我就会和朋友一起去参加活动。", pinyin: "Rúguǒ bǎ shíjiān ānpái hǎo, wǒ jiù huì hé péngyou yìqǐ qù cānjiā huódòng.", vi: "Nếu sắp xếp thời gian tốt, tôi sẽ cùng bạn tham gia hoạt động." },
    ],
  },
  4: {
    questions: [
      {
        id: "q4-experience",
        level: 4,
        hanzi: "你认为工作经验和学历哪个更重要？",
        pinyin: "Nǐ rènwéi gōngzuò jīngyàn hé xuélì nǎge gèng zhòngyào?",
        vi: "Bạn cho rằng kinh nghiệm làm việc và bằng cấp cái nào quan trọng hơn?",
      },
      {
        id: "q4-pressure",
        level: 4,
        hanzi: "现在的年轻人面临哪些压力？",
        pinyin: "Xiànzài de niánqīng rén miànlín nǎxiē yālì?",
        vi: "Người trẻ hiện nay đối mặt với những áp lực nào?",
      },
      {
        id: "q4-shopping",
        level: 4,
        hanzi: "网络购物给生活带来了什么变化？",
        pinyin: "Wǎngluò gòuwù gěi shēnghuó dàilái le shénme biànhuà?",
        vi: "Mua sắm trực tuyến mang lại thay đổi gì cho cuộc sống?",
      },
    ],
    vocabulary: [
      { word: "竞争", pinyin: "jìngzhēng", vi: "cạnh tranh", level: 4, difficulty: 2.3 },
      { word: "压力", pinyin: "yālì", vi: "áp lực", level: 4, difficulty: 2 },
      { word: "态度", pinyin: "tàidù", vi: "thái độ", level: 4, difficulty: 2 },
      { word: "独立", pinyin: "dúlì", vi: "độc lập", level: 4, difficulty: 2.1 },
      { word: "社会", pinyin: "shèhuì", vi: "xã hội", level: 4, difficulty: 1.9 },
      { word: "经济", pinyin: "jīngjì", vi: "kinh tế", level: 4, difficulty: 2.1 },
      { word: "效率", pinyin: "xiàolǜ", vi: "hiệu suất", level: 4, difficulty: 2.1 },
      { word: "质量", pinyin: "zhìliàng", vi: "chất lượng", level: 4, difficulty: 2.1 },
      { word: "挑战", pinyin: "tiǎozhàn", vi: "thách thức", level: 4, difficulty: 2.2 },
      { word: "责任", pinyin: "zérèn", vi: "trách nhiệm", level: 4, difficulty: 2 },
      { word: "目标", pinyin: "mùbiāo", vi: "mục tiêu", level: 4, difficulty: 2 },
      { word: "沟通", pinyin: "gōutōng", vi: "giao tiếp", level: 4, difficulty: 2 },
      { word: "观点", pinyin: "guāndiǎn", vi: "quan điểm", level: 4, difficulty: 2.1 },
      { word: "价值", pinyin: "jiàzhí", vi: "giá trị", level: 4, difficulty: 2.2 },
      { word: "意义", pinyin: "yìyì", vi: "ý nghĩa", level: 4, difficulty: 2 },
    ],
    grammar: [
      { id: "g4-budan", level: 4, label: "不但…而且…", pattern: /不但.*而且/ },
      { id: "g4-wulun", level: 4, label: "无论…都…", pattern: /无论.*都/ },
      { id: "g4-jishi", level: 4, label: "即使…也…", pattern: /即使.*也/ },
      { id: "g4-jiran", level: 4, label: "既然…就…", pattern: /既然.*就/ },
    ],
    fallbackAnswers: [
      { hanzi: "我认为两者都很重要，但是经验能更好地体现一个人的价值。", pinyin: "Wǒ rènwéi liǎng zhě dōu hěn zhòngyào, dànshì jīngyàn néng gèng hǎo de tǐxiàn yī gè rén de jiàzhí.", vi: "Tôi cho rằng cả hai đều quan trọng, nhưng kinh nghiệm thể hiện giá trị con người tốt hơn." },
      { hanzi: "无论竞争多么激烈，我们都应该保持积极的态度。", pinyin: "Wúlùn jìngzhēng duōme jīliè, wǒmen dōu yīnggāi bǎochí jījí de tàidù.", vi: "Dù cạnh tranh gay gắt thế nào, chúng ta vẫn nên giữ thái độ tích cực." },
    ],
  },
  5: {
    questions: [
      {
        id: "q5-ai",
        level: 5,
        hanzi: "你如何看待人工智能对就业市场的影响？",
        pinyin: "Nǐ rúhé kàndài réngōng zhìnéng duì jiùyè shìchǎng de yǐngxiǎng?",
        vi: "Bạn nhìn nhận thế nào về ảnh hưởng của AI tới thị trường việc làm?",
      },
      {
        id: "q5-tradition",
        level: 5,
        hanzi: "在你看来，传统文化应该如何与现代社会结合？",
        pinyin: "Zài nǐ kànlái, chuántǒng wénhuà yīnggāi rúhé yǔ xiàndài shèhuì jiéhé?",
        vi: "Theo bạn, văn hóa truyền thống nên kết hợp với xã hội hiện đại thế nào?",
      },
      {
        id: "q5-pressure",
        level: 5,
        hanzi: "有人说压力是动力，你是否同意？为什么？",
        pinyin: "Yǒurén shuō yālì shì dònglì, nǐ shìfǒu tóngyì? Wèishénme?",
        vi: "Có người nói áp lực là động lực, bạn có đồng ý không? Vì sao?",
      },
    ],
    vocabulary: [
      { word: "可持续", pinyin: "kěchíxù", vi: "bền vững", level: 5, difficulty: 2.8 },
      { word: "人工智能", pinyin: "réngōngzhìnéng", vi: "trí tuệ nhân tạo", level: 5, difficulty: 2.7 },
      { word: "就业", pinyin: "jiùyè", vi: "việc làm", level: 5, difficulty: 2.5 },
      { word: "市场", pinyin: "shìchǎng", vi: "thị trường", level: 5, difficulty: 2.4 },
      { word: "传统", pinyin: "chuántǒng", vi: "truyền thống", level: 5, difficulty: 2.4 },
      { word: "现代", pinyin: "xiàndài", vi: "hiện đại", level: 5, difficulty: 2.4 },
      { word: "趋势", pinyin: "qūshì", vi: "xu hướng", level: 5, difficulty: 2.6 },
      { word: "战略", pinyin: "zhànlüè", vi: "chiến lược", level: 5, difficulty: 2.7 },
      { word: "创新", pinyin: "chuàngxīn", vi: "đổi mới sáng tạo", level: 5, difficulty: 2.6 },
      { word: "资源", pinyin: "zīyuán", vi: "nguồn lực", level: 5, difficulty: 2.5 },
      { word: "政策", pinyin: "zhèngcè", vi: "chính sách", level: 5, difficulty: 2.5 },
      { word: "观念", pinyin: "guānniàn", vi: "quan niệm", level: 5, difficulty: 2.6 },
      { word: "潜力", pinyin: "qiánlì", vi: "tiềm lực", level: 5, difficulty: 2.6 },
      { word: "领域", pinyin: "lǐngyù", vi: "lĩnh vực", level: 5, difficulty: 2.6 },
      { word: "机制", pinyin: "jīzhì", vi: "cơ chế", level: 5, difficulty: 2.7 },
    ],
    grammar: [
      { id: "g5-yuqi", level: 5, label: "与其…不如…", pattern: /与其.*不如/ },
      { id: "g5-yaobu", level: 5, label: "要不是…", pattern: /要不是/ },
      { id: "g5-yiwei", level: 5, label: "以…为…", pattern: /以.+为/ },
      { id: "g5-nanmian", level: 5, label: "难免", pattern: /难免/ },
    ],
    fallbackAnswers: [
      { hanzi: "人工智能既带来挑战，也创造了新的就业机会。", pinyin: "Réngōng zhìnéng jì dàilái tiǎozhàn, yě chuàngzàole xīn de jiùyè jīhuì.", vi: "AI vừa mang lại thách thức vừa tạo cơ hội việc làm mới." },
      { hanzi: "与其担心被取代，不如主动学习新的技能。", pinyin: "Yǔqí dānxīn bèi qǔdài, bùrú zhǔdòng xuéxí xīn de jìnéng.", vi: "Thay vì lo bị thay thế, chi bằng chủ động học kỹ năng mới." },
    ],
  },
  6: {
    questions: [
      {
        id: "q6-sustain",
        level: 6,
        hanzi: "请谈谈你对可持续发展的理解，以及个人能做出哪些贡献。",
        pinyin: "Qǐng tántan nǐ duì kěchíxù fāzhǎn de lǐjiě, yǐjí gèrén néng zuòchū nǎxiē gòngxiàn.",
        vi: "Hãy trình bày hiểu biết của bạn về phát triển bền vững và đóng góp cá nhân.",
      },
      {
        id: "q6-education",
        level: 6,
        hanzi: "面对快速变化的社会，你认为教育体系需要做出哪些改革？",
        pinyin: "Miànduì kuàisù biànhuà de shèhuì, nǐ rènwéi jiàoyù tǐxì xūyào zuòchū nǎxiē gǎigé?",
        vi: "Trước xã hội biến đổi nhanh, bạn cho rằng hệ thống giáo dục cần cải cách gì?",
      },
      {
        id: "q6-global",
        level: 6,
        hanzi: "全球化背景下，如何平衡文化交流与文化认同之间的关系？",
        pinyin: "Quánqiúhuà bèijǐng xià, rúhé pínghéng wénhuà jiāoliú yǔ wénhuà rèntóng zhījiān de guānxi?",
        vi: "Trong bối cảnh toàn cầu hóa, làm sao cân bằng giao lưu văn hóa và bản sắc văn hóa?",
      },
    ],
    vocabulary: [
      { word: "全球化", pinyin: "quánqiúhuà", vi: "toàn cầu hóa", level: 6, difficulty: 2.7 },
      { word: "认同", pinyin: "rèntóng", vi: "đồng nhất/bản sắc", level: 6, difficulty: 2.8 },
      { word: "改革", pinyin: "gǎigé", vi: "cải cách", level: 6, difficulty: 2.8 },
      { word: "体系", pinyin: "tǐxì", vi: "hệ thống", level: 6, difficulty: 2.4 },
      { word: "贡献", pinyin: "gòngxiàn", vi: "đóng góp", level: 6, difficulty: 2.8 },
      { word: "平衡", pinyin: "pínghéng", vi: "cân bằng", level: 6, difficulty: 2.7 },
      { word: "培养", pinyin: "péiyǎng", vi: "bồi dưỡng", level: 6, difficulty: 2.6 },
      { word: "意识", pinyin: "yìshí", vi: "ý thức", level: 6, difficulty: 2.7 },
      { word: "文明", pinyin: "wénmíng", vi: "văn minh", level: 6, difficulty: 2.8 },
      { word: "伦理", pinyin: "lúnlǐ", vi: "luân lý", level: 6, difficulty: 2.9 },
      { word: "宏观", pinyin: "hóngguān", vi: "vĩ mô", level: 6, difficulty: 2.9 },
      { word: "辩证", pinyin: "biànzhèng", vi: "biện chứng", level: 6, difficulty: 2.9 },
      { word: "制约", pinyin: "zhìyuē", vi: "hạn chế/ràng buộc", level: 6, difficulty: 2.8 },
      { word: "演变", pinyin: "yǎnbiàn", vi: "diễn biến", level: 6, difficulty: 2.9 },
      { word: "融合", pinyin: "rónghé", vi: "hòa nhập", level: 6, difficulty: 2.8 },
    ],
    grammar: [
      { id: "g6-wufei", level: 6, label: "无非", pattern: /无非/ },
      { id: "g6-jianyu", level: 6, label: "鉴于", pattern: /鉴于/ },
      { id: "g6-hechang", level: 6, label: "何尝", pattern: /何尝/ },
      { id: "g6-bushiwei", level: 6, label: "不失为", pattern: /不失为/ },
      { id: "g6-yuyu", level: 6, label: "愈…愈…", pattern: /愈.+愈/ },
    ],
    fallbackAnswers: [
      { hanzi: "鉴于资源有限，可持续发展无非是全人类共同的责任。", pinyin: "Jiànyú zīyuán yǒuxiàn, kěchíxù fāzhǎn wúfēi shì quán rénlèi gòngtóng de zérèn.", vi: "Bởi nguồn lực hữu hạn, phát triển bền vững chẳng qua là trách nhiệm chung của nhân loại." },
      { hanzi: "全球化既是机遇，也是文化认同面临的挑战。", pinyin: "Quánqiúhuà jì shì jīyù, yě shì wénhuà rèntóng miànlín de tiǎozhàn.", vi: "Toàn cầu hóa vừa là cơ hội, vừa là thách thức cho bản sắc văn hóa." },
    ],
  },
}

export const HSK_BAND_THRESHOLDS = [
  { band: 1, min: 0, max: 1.5 },
  { band: 2, min: 1.5, max: 2.5 },
  { band: 3, min: 2.5, max: 3.5 },
  { band: 4, min: 3.5, max: 4.5 },
  { band: 5, min: 4.5, max: 5.5 },
  { band: 6, min: 5.5, max: Infinity },
]
